# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "stock_analytics"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  stock_analytics:
    # Staging models - clean and standardize raw data
    staging:
      +schema: staging
      +materialized: view

    # Intermediate models - business logic and calculations
    intermediate:
      +schema: staging  # Keep intermediate in staging
      +materialized: view

    # Marts - final analytics-ready tables
    marts:
      +schema: marts
      +materialized: table
      dimensions:
        +schema: marts
        +materialized: table
      facts:
        +schema: marts
        +materialized: table
      analytics:
        +schema: marts
        +materialized: table